# Default values for signalfx-smart-gateway.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# nameOverride -- overrides the name of the helm chart
nameOverride: ""
# fullnameOverride -- overrides the full name of the helm chart
fullnameOverride: ""

# image -- configurations for the deployed docker image
image:
  # image.pullPolicy -- defines when to pull the image
  pullPolicy: IfNotPresent
  # image.repository -- the container image to pull
  repository: signalfx-smart-gateway
  # image.tag -- the container image tag to pull (REQUIRED)
  tag: ""
  # image.pullSecrets -- the image pull secrets of kubernetes secrets to use when pulling images  (REQUIRED)
  pullSecrets:
    - name: ""

# signalFxAccessToken -- access token for SignalFx.  (REQUIRED)
signalFxAccessToken: ""

# clusterName -- the name of the cluster (REQUIRED)
clusterName: ""

# targetClusterAddresses -- (list) a list of etcd client addresses to connect to (REQUIRED)
targetClusterAddresses:

# listeners -- SignalFx Gateway listener config objects.  These will be merged into the gateway.conf.ListenFrom list.
listeners: [
  # listeners[0] -- The default SiganlFx listener
  {
      # listeners[0].Name -- the name of the SignalFx Listener
      "Name": "signalfxlistener",
      # listeners[0].Type -- the type of the SignalFxListener
      "Type": "signalfx",
      # listeners[0].ListenAddr -- the address for the SignalFx Listener to listen on
      "ListenAddr": "0.0.0.0:18080",
      # listeners[0].RemoveSpanTags -- the list of span tags for the SignalFx Listener to remove
      "RemoveSpanTags": []
  }
]

# forwarders -- additional SignalFx Gateway forwarder config objects.  These will be merged into the gateway.conf.ForwardTo list.
forwarders: []

# gateway -- configurations for gateway nodes
gateway:
  # gateway.count -- number of gateway pods to deploy
  count: 1
  # gateway.advertisedSFXListenerAddress -- is an environment variable that will be set in the gateway pod. It is used to configure SignalFx Smart Samplers to advertise their configured SignalFx Listener in the cluster. By default it is set to the $(POD_IP):<PORT> where this config specifies the port, and the "$(POD_IP)" is filled in by kubernetes
  advertisedSFXListenerAddress: $(POD_IP):18080
  # gateway.advertisedSFXRebalanceAddress -- is an environment variable that will be set in the gateway pod.  It is used to configure the SignalFx Smart Samplers to advertise their configured RebalanceAddress in the cluister.  By defaul it is set to the $(POD_IP):<PORT> where this config specifies the port, and the "$(POD_IP)" is filled in by kubernetes
  advertisedSFXRebalanceAddress: $(POD_IP):2382
  # gateway.conf -- represents the SignalFx Smart Gateway's config file.  You can directly set additional configurations `--set gateway.conf.<GATEAY CONFIG KEY>=`
  conf: 
    # gateway.conf.LogDir -- the directory to log to.  A value of "-" will log to stdout
    LogDir: "-"
    # gateway.conf.ListenFrom -- the gateway listeners.  This list is merged with the listeners list.
    ListenFrom: []
    # gateway.conf.ForwardTo -- the gateway forwarders.  This list is merged with the forwarders list.
    ForwardTo: [
      # gateway.conf.ForwardTo[0] -- the default SignalFx forwarder
      {
        # gateway.conf.ForwardTo[0].Name -- the name of the SignalFx forwarder
        "Name": "signalfxforwarder",
        # gateway.conf.ForwardTo[0].Type -- the type of the SignalFx forwarder
        "Type": "signalfx",
        # gateway.conf.ForwardTo[0].AuthTokenEnvVar -- the environment variable to read for the SignalFx Access Token
        "AuthTokenEnvVar": "SFX_AUTH_TOKEN",
        # gateway.conf.ForwardTo[0].TraceSample -- configurations for the SignalFx Smart Sampler
        "TraceSample": {
          # gateway.conf.ForwardTo[0].TraceSample.ListenRebalanceAddress -- the address to listen on for cluster rebalances
          "ListenRebalanceAddress": "0.0.0.0:2382",
          # gateway.conf.ForwardTo[0].TraceSample.BackupLocation -- the location inside the container to back up sampling data
          "BackupLocation": "/var/lib/gateway/data"
        }
      }
    ]
  # gateway.containerPorts -- a list of kubernetes container port definitions apply to the container
  containerPorts:
    # gateway.containerPorts[0].name -- the name of the SignalFx Listener containerPort
  - name: sfx-listener
    # gateway.containerPorts[0].containerPort -- the container port of the SignalFx Listener
    containerPort: 18080
    # gateway.containerPorts[0].protocol -- the protocol of the SignalFx Listener
    protocol: TCP
    # gateway.containerPorts[1].name -- the name of the SignalFx Forwarder's rebalance containerPort
  - name: sfx-rebalance
    # gateway.containerPorts[1].containerPort -- the container port of the SignalFx Forwarder's rebalance server
    containerPort: 2382
    # gateway.containerPorts[1].protocol -- the protocol of the SignalFx Forwarder's rebalance server
    protocol: TCP
  # gateway.livenessProbe -- a kubernetes liveness probe to determine the health of the container
  livenessProbe:
    httpGet:
      path: /healthz
      port: sfx-listener
    initialDelaySeconds: 15
  # gateway.readinessProbe -- a kubernetes readiness probe to determine when the container is ready
  readinessProbe: {}
  # gateway.resources -- kubernetes deployment resources
  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi
  # gateway.nodeSelector -- kubernetes node selectors to apply to the pod
  nodeSelector: {}
  # gateway.tolerations -- kubernetes deployment tolerations to apply to the pod
  tolerations: []
  # gateway.affinity -- kubernetes affinity configuriations to apply to the pod
  affinity: {}
  # gateway.volumes -- kubernetes volumes to apply to the pod
  volumes: []
  # gateway.volumeMounts -- kubernetes volume mounts to apply to the container
  volumeMounts: []
  # gateway.volumeClaimTemplates -- volume claim templates to attach to replicas
  volumeClaimTemplates: []

# service -- configurations for the service exposeing the gateway's SignalFx listener
service:
  # service.type -- the type of service
  type: ClusterIP
  # service.ports -- the ports to configure on the service
  ports:
      # service.ports[0].port -- the port to use on the service
    - port: 18080
      # service.ports[0].targetPort -- the name of the container port to send requests to
      targetPort: sfx-listener
      # service.ports[0].protocol -- the protocol of the service
      protocol: TCP
      # service.ports[0].nameSuffix -- a suffix to apply to the port name
      nameSuffix: sfx-listener

ingress:
  enabled: false
