{{- range $key, $value := .Values }}{{ if (or (eq $key "gateway") (eq $key "distributor")) }}{{ with $value }}
---
# distributor configmap
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "signalfx-smart-gateway.fullname" $ }}{{if (eq $key "distributor") }}-{{ $key }}{{ end }}
  labels:
    signalfx-gateway-type: {{ $key }}
{{ include "signalfx-smart-gateway.labels" $ | indent 4 }}
data:
  gateway.conf: |
    {
      {{- if .ClusterName }}
      "ClusterName": {{ toJson .ClusterName }},
      {{ else }}
      "ClusterName": {{ toJson $.Values.clusterName}},
      {{- end }}
      {{- range $k, $v := .conf}}{{ if not (eq $k "Listeners" "Forwarders" "TargetClusterAddresses" "ClusterName")}}
      "{{ $k }}": {{ toJson $v }},
      {{- end }}{{ end }}
      "TargetClusterAddresses": [
        {{- if .conf.TargetClusterAddresses }}
        {{- range $index, $addr := .conf.TargetClusterAddresses }}
        {{- if $index}},{{- end }}
        {{toJson $addr}}
        {{- end }}
        {{- end }}
        {{- if $.Values.targetClusterAddresses }}
        {{- range $index, $addr := $.Values.targetClusterAddresses}}
        {{- if $index}},{{- end }}
        {{toJson $addr}}
        {{- end }}
        {{- end }}
      ],
      "ListenFrom": [
        {{- if .conf.ListenFrom }}
        {{- range $index, $listener := .conf.ListenFrom }}
        {{- if $index}},{{- end }}
        {{toJson $listener}}
        {{- end }}
        {{- else }}
        {{- range $index, $listener := $.Values.listeners }}
        {{- if $index}},{{- end }}
        {{toJson $listener}}
        {{- end }}
        {{- end }}
      ],
      "ForwardTo": [
        {{- if .conf.ForwardTo }}
        {{- range $index, $forwarder := .conf.ForwardTo }}
        {{- if $index}},{{- end }}
        {{toJson $forwarder}}
        {{- end }}
        {{- else }}
        {{- range $index, $forwarder := $.Values.forwarders }}
        {{- if $index}},{{- end }}
        {{toJson $forwarder}}
        {{- end }}
        {{- end }}
      ]
    }
{{- end }}{{ end }}{{ end }}
