apiVersion: v1
kind: Secret
metadata:
  name: {{ template "signalfx-smart-gateway.fullname" . }}
  labels:
{{ include "signalfx-smart-gateway.labels" $ | indent 4 }}
type: Opaque
data:
  access-token: {{ required "must specify an access token" .Values.signalFxAccessToken | b64enc | quote }}
